/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegrafica;

import javax.swing.DefaultListModel;

/**
 *
 * @author TALITANAIBERTDACOSTA
 */
public class pokedex extends javax.swing.JFrame {

    private static int[] getSelectedIndices() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form pokedex
     */
    
    
        DefaultListModel<String> modelo = new DefaultListModel<>();
        DefaultListModel<String> modelo2 = new DefaultListModel<>();
    public pokedex() {
        initComponents();
        
         computer.setModel(modelo);
        backpack.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionarPokemon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        computer = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        backpack = new javax.swing.JList<>();
        adicionar = new javax.swing.JToggleButton();
        Return_to_computer = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pokemon = new javax.swing.JTextField();
        add_to_backpack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionarPokemon.setBackground(new java.awt.Color(0, 0, 0));

        computer.setBackground(new java.awt.Color(0, 0, 0));
        computer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        computer.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(computer);

        backpack.setBackground(new java.awt.Color(0, 0, 0));
        backpack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        backpack.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(backpack);

        adicionar.setBackground(new java.awt.Color(0, 0, 0));
        adicionar.setForeground(new java.awt.Color(255, 255, 255));
        adicionar.setText("adicionar");
        adicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102), 3));
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        Return_to_computer.setBackground(new java.awt.Color(0, 0, 0));
        Return_to_computer.setForeground(new java.awt.Color(255, 255, 255));
        Return_to_computer.setText("Return to computer");
        Return_to_computer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102), 3));
        Return_to_computer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_to_computerActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("pokemons");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("pokedex");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("computer");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("backpack");

        pokemon.setBackground(new java.awt.Color(0, 0, 0));
        pokemon.setForeground(new java.awt.Color(255, 255, 255));
        pokemon.setText("seu pokemon...");
        pokemon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        add_to_backpack.setBackground(new java.awt.Color(0, 0, 0));
        add_to_backpack.setForeground(new java.awt.Color(255, 255, 255));
        add_to_backpack.setText("add to backpack");
        add_to_backpack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102), 3));
        add_to_backpack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_backpackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adicionarPokemonLayout = new javax.swing.GroupLayout(adicionarPokemon);
        adicionarPokemon.setLayout(adicionarPokemonLayout);
        adicionarPokemonLayout.setHorizontalGroup(
            adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarPokemonLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adicionarPokemonLayout.createSequentialGroup()
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adicionarPokemonLayout.createSequentialGroup()
                                .addComponent(adicionar)
                                .addGap(687, 687, 687)
                                .addComponent(Return_to_computer))
                            .addGroup(adicionarPokemonLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(507, 507, 507)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adicionarPokemonLayout.createSequentialGroup()
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_to_backpack)
                            .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pokemon)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(396, 396, 396))))
        );
        adicionarPokemonLayout.setVerticalGroup(
            adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarPokemonLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarPokemonLayout.createSequentialGroup()
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarPokemonLayout.createSequentialGroup()
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(69, 69, 69)))
                .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adicionarPokemonLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(adicionarPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Return_to_computer)
                            .addComponent(adicionar)
                            .addComponent(add_to_backpack))))
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adicionarPokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adicionarPokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
       String newPokemon = pokemon.getText().trim();//tira espaço da lista
        //se o campo n estiver vazio
        if(!newPokemon.isEmpty()){
            modelo.addElement(newPokemon);//adicionar modelo
            pokemon.setText("");//limpa o campo
            
            
            

add_to_backpack.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        // Obter o Pokémon selecionado na lista "Computador"
        String pokemonSelecionado = computer.getSelectedValue();

        // Remover o Pokémon do modelo da lista "Computador"
        modelo.removeElement(pokemonSelecionado);

        // Adicionar o Pokémon ao modelo da lista "Mochila"
        backpack.setModel(modelo2); // Assumindo que o modelo da mochila é o mesmo
        modelo.addElement(pokemonSelecionado);

        // Atualizar as listas na interface gráfica
     
        backpack.setModel(modelo2);
    }
});



        }
    }//GEN-LAST:event_adicionarActionPerformed

    private void Return_to_computerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_to_computerActionPerformed

Return_to_computer.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
           int [] selectedIndices = pokedex.getSelectedIndices();
   
   
   if(selectedIndices.length > 0){
       for (int i = selectedIndices.length - 1; i >=0; i--){
           
           int index = selectedIndices[i];
           
       }
   }        
        // Obter o Pokémon selecionado na lista "Mochila"
        String pokemonSelecionado = backpack.getSelectedValue();

        // Remover o Pokémon do modelo da lista "Mochila"
        modelo.removeElement(pokemonSelecionado);

        // Adicionar o Pokémon ao modelo da lista "Computador"
        computer.setModel(modelo); // Assumindo que o modelo do computador é o mesmo
        modelo.addElement(pokemonSelecionado);

        // Atualizar as listas na interface gráfica
        computer.setModel(modelo);
        
       
    }
});



    }//GEN-LAST:event_Return_to_computerActionPerformed

    private void add_to_backpackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_backpackActionPerformed
    int[]  selectedIndices = backpack.getSelectedIndices();
        
    }//GEN-LAST:event_add_to_backpackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokedex().setVisible(true);
                
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Return_to_computer;
    private javax.swing.JButton add_to_backpack;
    private javax.swing.JToggleButton adicionar;
    private javax.swing.JPanel adicionarPokemon;
    private javax.swing.JList<String> backpack;
    private javax.swing.JList<String> computer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pokemon;
    // End of variables declaration//GEN-END:variables
}
